export const CartActionsTypes = {
        TOOGLE_CART_HIDDEN: 'TOOGLE_CART_HIDDEN',
        ADD_ITEM:'ADD_ITEM',
        REMOVE_ITEM: 'REMOVE_ITEM',     
        REMOVE_ITEM_CHECKOUT: ' REMOVE_ITEM_CHECKOUT'
}